import os
from pathlib import Path
from typing import Dict, Any
from langchain.messages import AIMessage
from supervisor_worker.local_states._state_ import AgentState


def generate(state: AgentState) -> Dict[str, Any]:
    output_dir = Path(state["output_dir"])
    final_dir = output_dir / "final_deliverables"
    final_dir.mkdir(parents=True, exist_ok=True)

    ba_output = state.get("ba_output") or {}
    ixd_output = state.get("ixd_output") or {}

    index_lines = [
        "# Master Requirements & Design Package\n",
        "## Executive Summary\n",
        "This deliverable package contains the approved Business Analysis specification and Interaction Design mockups generated by the Supervisor-Worker multi-agent pipeline.\n",
        "---\n",
        "## Package Index\n",
    ]

    # 1. BA Summary
    user_needs = ba_output.get("user_needs", [])
    user_stories = ba_output.get("user_stories", [])
    fr_count = len(ba_output.get("functional_requirements", []))
    nfr_count = len(ba_output.get("non_functional_requirements", []))

    index_lines.append("### 1. Requirements Specification")
    index_lines.append(f"- **Discovered User Needs:** {len(user_needs)}")
    index_lines.append(f"- **Functional Requirements:** {fr_count}")
    index_lines.append(f"- **Non-Functional Requirements:** {nfr_count}")
    index_lines.append(f"- **Agile User Stories:** {len(user_stories)}\n")

    # 2. IxD Summary
    mockup_files = ixd_output.get("mockup_files", {}).get("files", [])
    tradeoffs = ixd_output.get("tradeoffs", {}).get("table", [])

    index_lines.append("### 2. Interaction Design Mockups")
    index_lines.append(f"- **HTML Mockup Screens:** {len(mockup_files)}")
    index_lines.append(f"- **UI/UX Trade-off Decisions:** {len(tradeoffs)}\n")

    # Copy / save HTML mockups to final_deliverables folder if available
    if mockup_files:
        mockups_dir = final_dir / "mockups"
        mockups_dir.mkdir(exist_ok=True)
        for mockup in mockup_files:
            file_name = mockup.get("file_name", "mockup.html")
            code = mockup.get("html_code", "")
            (mockups_dir / file_name).write_text(code, encoding="utf-8")
        index_lines.append(f"HTML mockups have been exported to `./mockups/`\n")

    index_lines.append("---\n*Status: Fully Reviewed & Approved by Supervisor Agent*")

    (final_dir / "INDEX.md").write_text("\n".join(index_lines), encoding="utf-8")
    print(f"[Compiler] Final deliverables compiled to '{final_dir.resolve()}'")

    return {
        "phase": "completed",
        "messages": [
            AIMessage(
                content=f"Workflow completed successfully. Approved deliverables packaged at '{final_dir.resolve()}'"
            )
        ],
    }
